name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.3.0"

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Build project
        run: npm run build

      - name: Export project
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          exclude_assets: ".nojekyll"

      - name: Disable Jekyll
        run: touch out/.nojekyll
